function [bytes_to_samples_cell] = bytes_to_samples_func;
 %% [bytes_to_samples_cell] = bytes_to_samples_func;
 % Returns the array describing how trace headers in SEGY files 
 % are organized
 
 bytes_to_samples_cell = {...
 4   [  1]    'TraceNumWithinLine';        
 4   [  5]    'TraceNumWithinFile';           
 4   [  9]    'FieldRecord';          
 4   [ 13]    'TraceNumber';                  
 4   [ 17]    'EnergySourcePoint';            
 4   [ 21]    'CDP';                          
 4   [ 25]    'CDPTrace';                     
 2   [ 29]    'TraceIDCode';                  
 2   [ 31]    'NSummedTraces';                
 2   [ 33]    'NStackedTraces';               
 2   [ 35]    'DataUse';                      
 4   [ 37]    'Offset';                      
 4   [ 41]    'RecGroupElevation';            
 4   [ 45]    'SourceSurfaceElevation';       
 4   [ 49]    'SourceDepth';                  
 4   [ 53]    'RecDatumElevation';            
 4   [ 57]    'SourceDatumElevation';         
 4   [ 61]    'SourceWaterDepth';             
 4   [ 65]    'GroupWaterDepth';              
 2   [ 69]    'ElevationScalar';              
 2   [ 71]    'RecSourceScalar';              
 4   [ 73]    'SourceX';                      
 4   [ 77]    'SourceY';                      
 4   [ 81]    'GroupX';                       
 4   [ 85]    'GroupY';                       
 2   [ 89]    'CoordUnits';                   
 2   [ 91]    'WeatheringVelocity';           
 2   [ 93]    'SubWeatheringVelocity';        
 2   [ 95]    'UpholeTimeSource';             
 2   [ 97]    'UpholeTimeGroup';              
 2   [ 99]    'StaticCorrectionSource';       
 2   [101]    'StaticCorrectionGroup';        
 2   [103]    'TotalStaticApplied';           
 2   [105]    'LagTimeA';                     
 2   [107]    'LagTimeB';                     
 2   [109]    'DelayRecordingTime';           
 2   [111]    'MuteTimeStart';                
 2   [113]    'MuteTimeEnd';                  
 2   [115]    'ns';                           
 2   [117]    'dt';                           
 2   [119]    'GainType';                     
 2   [121]    'InstrumentGainConstant';       
 2   [123]    'InstrumntInitialGain';         
 2   [125]    'Correlated';                   
 2   [127]    'SweepFrequencyStart';          
 2   [129]    'SweepFrequencyEnd';            
 2   [131]    'SweepLength';                  
 2   [133]    'SweepType';                    
 2   [135]    'SweepTraceTaperLengthStart';   
 2   [137]    'SweepTraceTaperLengthEnd';     
 2   [139]    'TaperType';                    
 2   [141]    'AliasFilterFrequency';         
 2   [143]    'AliasFilterSlope';             
 2   [145]    'NotchFilterFrequency';         
 2   [147]    'NotchFilterSlope';             
 2   [149]    'LowCutFrequency';              
 2   [151]    'HighCutFrequency';             
 2   [153]    'LowCutSlope';                  
 2   [155]    'HighCutSlope';                 
 2   [157]    'Year';                         
 2   [159]    'DayOfYear';                    
 2   [161]    'HourOfDay';                    
 2   [163]    'MinuteOfHour';                 
 2   [165]    'SecondOfMinute';               
 2   [167]    'TimeCode';                     
 2   [169]    'TraceWeightingFactor';         
 2   [171]    'GeophoneGroupNumberRoll';      
 2   [173]    'GeophoneGroupNumberTraceStart';
 2   [175]    'GeophoneGroupNumberTraceEnd';  
 2   [177]    'GapSize';                     
 2   [179]    'OverTravel';                   
 4   [181]    'CDPX';                         
 4   [185]    'CDPY';                         
 4   [189]    'Inline3D';                     
 4   [193]    'Crossline3D';                  
 4   [197]    'ShotPoint';                    
 2   [201]    'ShotPointScalar';              
 2   [203]    'TraceValueMeasurmentUnit';     
 4   [205]    'TransductionConstnatMantissa'; 
 2   [209]    'TransductionConstantPower';    
 2   [211]    'TransductionUnit';             
 2   [213]    'TraceIdentifier';              
 2   [215]    'ScalarTraceHeader';            
 2   [217]    'SourceType';                   
 4   [219]    'SourceEnergyDirectionMantissa';
 2   [223]    'SourceEnergyDirectionExponent';
 4   [225]    'SourceMeasurmentMantissa';     
 2   [229]    'SourceMeasurementExponent';    
 2   [231]    'SourceMeasurmentUnit';         
 4   [233]    'Unassigned1';                  
 4   [237]    'Unassigned2'};                  


