 function [bytes_to_samples_cell] = bytes_to_samples_func;
 %% [bytes_to_samples_cell] = bytes_to_samples_func;
 % Returns the array describing how trace headers in SEGY files 
 % are organized
 
 bytes_to_samples_cell = {...
    [  1]    'TraceNumWithinLine';        
    [  5]    'TraceNumWithinFile';           
    [  9]    'FieldRecord';          
    [ 13]    'TraceNumber';                  
    [ 17]    'EnergySourcePoint';            
    [ 21]    'CDP';                          
    [ 25]    'CDPTrace';                     
    [ 29]    'TraceIDCode';                  
    [ 31]    'NSummedTraces';                
    [ 33]    'NStackedTraces';               
    [ 35]    'DataUse';                      
    [ 37]    'Offset';                      
    [ 41]    'RecGroupElevation';            
    [ 45]    'SourceSurfaceElevation';       
    [ 49]    'SourceDepth';                  
    [ 53]    'RecDatumElevation';            
    [ 57]    'SourceDatumElevation';         
    [ 61]    'SourceWaterDepth';             
    [ 65]    'GroupWaterDepth';              
    [ 69]    'ElevationScalar';              
    [ 71]    'RecSourceScalar';              
    [ 73]    'SourceX';                      
    [ 77]    'SourceY';                      
    [ 81]    'GroupX';                       
    [ 85]    'GroupY';                       
    [ 89]    'CoordUnits';                   
    [ 91]    'WeatheringVelocity';           
    [ 93]    'SubWeatheringVelocity';        
    [ 95]    'UpholeTimeSource';             
    [ 97]    'UpholeTimeGroup';              
    [ 99]    'StaticCorrectionSource';       
    [101]    'StaticCorrectionGroup';        
    [103]    'TotalStaticApplied';           
    [105]    'LagTimeA';                     
    [107]    'LagTimeB';                     
    [109]    'DelayRecordingTime';           
    [111]    'MuteTimeStart';                
    [113]    'MuteTimeEnd';                  
    [115]    'ns';                           
    [117]    'dt';                           
    [119]    'GainType';                     
    [121]    'InstrumentGainConstant';       
    [123]    'InstrumntInitialGain';         
    [125]    'Correlated';                   
    [127]    'SweepFrequencyStart';          
    [129]    'SweepFrequencyEnd';            
    [131]    'SweepLength';                  
    [133]    'SweepType';                    
    [135]    'SweepTraceTaperLengthStart';   
    [137]    'SweepTraceTaperLengthEnd';     
    [139]    'TaperType';                    
    [141]    'AliasFilterFrequency';         
    [143]    'AliasFilterSlope';             
    [145]    'NotchFilterFrequency';         
    [147]    'NotchFilterSlope';             
    [149]    'LowCutFrequency';              
    [151]    'HighCutFrequency';             
    [153]    'LowCutSlope';                  
    [155]    'HighCutSlope';                 
    [157]    'Year';                         
    [159]    'DayOfYear';                    
    [161]    'HourOfDay';                    
    [163]    'MinuteOfHour';                 
    [165]    'SecondOfMinute';               
    [167]    'TimeCode';                     
    [169]    'TraceWeightingFactor';         
    [171]    'GeophoneGroupNumberRoll';      
    [173]    'GeophoneGroupNumberTraceStart';
    [175]    'GeophoneGroupNumberTraceEnd';  
    [177]    'GapSize';                     
    [179]    'OverTravel';                   
    [181]    'CDPX';                         
    [185]    'CDPY';                         
    [189]    'Inline3D';                     
    [193]    'Crossline3D';                  
    [197]    'ShotPoint';                    
    [201]    'ShotPointScalar';              
    [203]    'TraceValueMeasurmentUnit';     
    [205]    'TransductionConstnatMantissa'; 
    [209]    'TransductionConstantPower';    
    [211]    'TransductionUnit';             
    [213]    'TraceIdentifier';              
    [215]    'ScalarTraceHeader';            
    [217]    'SourceType';                   
    [219]    'SourceEnergyDirectionMantissa';
    [223]    'SourceEnergyDirectionExponent';
    [225]    'SourceMeasurmentMantissa';     
    [229]    'SourceMeasurementExponent';    
    [231]    'SourceMeasurmentUnit';         
    [233]    'Unassigned1';                  
    [237]    'Unassigned2'};                  


